candidates/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

candidates/candidates/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('lk.urls')),
    path('about/', include('about.urls', namespace='about')),
]

candidates/lk/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:username>/', views.profile, name='profile'),
    path('api/delete/<int:id>', views.delete),
]

candidates/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"), 
]

candidates/lk/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Tag(models.Model):
    name = models.CharField(
        'tag',
        max_length=200,
        null=True,
        unique=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Skill(models.Model):
    candidate = models.ManyToManyField(
        User,
        related_name='skills',
    )
    tag = models.ForeignKey(
        Tag,
        on_delete=models.CASCADE,
        related_name="skills",
        null=True,
    )
    name = models.CharField(
        'название навыка',
        max_length=200,
        null=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('tag', 'name',)
        unique_together = ('tag', 'name')

candidates/lk/forms.py
from django import forms

from lk.fields import ListTextWidget
from lk.models import Skill, Tag


class FormForm(forms.Form):
    tag = forms.CharField(label='Тэги', required=True)
    skill = forms.CharField(label='Навыки', required=True)

    def __init__(self, *args, **kwargs):
        super(FormForm, self).__init__(*args, **kwargs)

        self.fields['tag'].widget = ListTextWidget(
            data_list=Tag.objects.all(),
            name='tag_list'
        )
        self.fields['skill'].widget = ListTextWidget(
            data_list=Skill.objects.all(),
            name='skill_list'
        )

candidates/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

candidates/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

candidates/lk/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import FormForm
from .models import Skill, Tag, User


def index(request):
    users = User.objects.prefetch_related('skills__tag', 'skills').order_by('id')
    paginator = Paginator(users, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(
         request,
         'index.html',
         {'page': page, }
    )


def profile(request, username):
    candidate = get_object_or_404(User, username=username)
    skill_list = Skill.objects.filter(
        candidate=candidate
    ).prefetch_related('tag')
    if request.method == "POST":
        form = FormForm(request.POST)
        if form.is_valid():
            tag, _ = Tag.objects.get_or_create(name=form.cleaned_data['tag'])
            skill, _ = Skill.objects.get_or_create(
                name=form.cleaned_data['skill'],
                tag=tag
            )
            skill.candidate.add(candidate)
            skill.tag = tag
            skill.save()
            return redirect('profile', username=request.user.username)
    else:
        form = FormForm()
    return render(
        request,
        'profile.html',
        {'candidate': candidate,
         'skill_list': skill_list,
         'form': form,
         },
    )


def delete(request, id):
    qs = Skill.objects.filter(id=id, candidate__id=request.user.id)
    if qs.exists():
        qs.delete()
    return redirect('profile', username=request.user.username)

candidates/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('index')
    template_name = "users/signup.html"

candidates/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                Об авторе
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Полезный короткий текст
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>Текст страницы "Об авторе"</p>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

candidates/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
<main role="main" class="container">
  <div class="row">
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                Об авторе
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Полезный короткий текст
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>Текст страницы "Об авторе"</p>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

candidates/templates/base.html
<!doctype html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %} | candidate list</title>
  {% load static %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
  </script>
</head>

<body>
  {% include 'nav.html' %}
  <main>
    <div class="container">
      <h1>{% block header %}{% endblock %}</h1>
      {% block content %}
      {% endblock %}
    </div>
  </main>
  {% include 'footer.html' %}
</body>

</html>

candidates/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center " style="text-align: center;">&nbsp; <span style="color: #000000;"><a
                style="color: #000000;" href="{% url 'about:author' %}">Об авторе</a></span></p>
    <p class="m-0 text-dark text-center " style="text-align: center;">&nbsp;<span style="color: #000000;"> <a
                style="color: #000000;" href="{% url 'about:tech' %}">Технологии</a></span></p>
</footer>

candidates/templates/index.html
{% extends "base.html" %}
{% block title %}Список кандидатов{% endblock %}

{% block content %}
<div class="container">
  <div class="h2"> Список кандидатов</div>
  <br>
  {% for user in page %}
  <div class="card mb-3 mt-1 shadow-sm">
    <div class="card-body">
      <p class="card-text">
        <a class="p text-dark" href="{% url 'profile' user.username %}"><strong
            class="d-block text-gray-dark">{{ user.get_full_name }}</strong></a>
      </p>
      {% regroup user.skills.all by tag as grouped_skills %}
      <ul>
        {% for group in grouped_skills %}
        <li>{{ group.grouper }}
          <ul>
            {% for skill in group.list %}
            <li>{{ skill.name }}</li>
            {% endfor %}
          </ul>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% if not forloop.last %}
  <hr>{% endif %}
  {% endfor %}
  {% include "paginator.html" %}
  {% endblock %}
</div>

candidates/templates/nav.html
<nav class="navbar navbar-dark bg-dark" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:rgb(255, 255, 255)">candidate list</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
    <a class="p-2 text-light" href="{% url 'profile' user.username %}">Ваш профиль</a>
    <a class="p-2 text-light" href="{% url 'password_change' %}">Изменить пароль</a>
    <a class="p-2 text-light" href="{% url 'logout' %}">Выйти</a>
    {% else %}
    <a class="p-2 text-light" href="{% url 'login' %}">Войти</a> |
    <a class="p-2 text-light" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

candidates/templates/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

candidates/templates/profile.html
{% extends "base.html" %}
{% block title %}{{ request.user}}{% endblock %}
{% block content %}
{% load user_filters %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Кандидат:</div>
      <div class="card-body">
        <div class="h4">{{ candidate.get_full_name }}</div>
        <div class="h5 text-muted"> {{ candidate.username}} </div>
        <br>
        Навыки:
        {% regroup skill_list by tag as grouped_skills %}
        <ul>
          {% for group in grouped_skills %}
          <li>{{ group.grouper }}
            <ul>
              {% for skill in group.list %}
              <li>{{ skill.name }} <a href="/api/delete/{{skill.id}}">x</a></li>
              {% endfor %}
            </ul>
          </li>
          {% endfor %}
        </ul>
        {% if request.user == candidate %}
        Добавьте навыки в профиль:
        <form method="post">
          {% csrf_token %}
          <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
            <label for="{{ field.id_for_label }}"
              class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
            <div class="col-md-6">
              {{ form.as_p }}
            </div>
          </div>
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-secondary btn-sm">
              Добавить навык
            </button>
          </div>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

candidates/users/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Зарегистрироваться</div>
      <div class="card-body">

        {% for error in form.errors %}
        <div class="alert alert-danger" role="alert">
          {{ error }}
        </div>
        {% endfor %}

        <form method="post" action="{% url 'signup' %}">
          {% csrf_token %}

          {% for field in form %}
          <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
            <label for="{{ field.id_for_label }}"
              class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span
                class="required">*</span>{% endif %}</label>
            <div class="col-md-6">
              {{ field|addclass:"form-control" }}
              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
              {% endif %}
            </div>
          </div>
          {% endfor %}

          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Зарегистрироваться
            </button>
          </div>
        </form>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->

{% endblock %}